language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  # 在 GitHub 上生成的 token，允许 Travis 推送代码到你的仓库。
  # 在仓库的 Travis 设置页面，设为安全的环境变量
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: ph


sudo: false
language: node_js
node_js:
  - "14" # use nodejs v10 LTS
cache:
  yarn: true
  npm: true
  directories:
    - node_modules
branches:
  only:
    - main # build master branch only
install:
  - yarn
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public